name: "Deploy GitHub Pages"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
        
    steps:
        - name: Configure git credentials
          uses: OleksiyRudenko/gha-git-credentials@v2.1.1
          with:
            token: '${{ secrets.GITHUB_TOKEN }}'

        - uses: actions/checkout@v3

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
        
        - run: npm ci
        - run: npm run build
        - run: npm run deploy